name: glowmatch
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  supabase_flutter: ^2.5.4
  geolocator: ^11.0.0
  http: ^1.2.1
  camera: ^0.10.5+9
  google_mlkit_text_recognition: ^0.12.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.5
  google_fonts: ^8.1.0
  fl_chart: ^0.66.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_padded.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo_padded.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo_padded.png

