// Mocks generated by Mockito 5.4.6 from annotations
// in glowmatch/test/core/services/sqlite_sync_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:glowmatch/core/models/models.dart' as _i5;
import 'package:glowmatch/core/services/database_helper.dart' as _i3;
import 'package:glowmatch/core/services/sync_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i3.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i4.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i4.Future<_i2.Database>);

  @override
  _i4.Future<List<_i5.ShelfItem>> getShelfItems(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getShelfItems, [userId]),
            returnValue: _i4.Future<List<_i5.ShelfItem>>.value(
              <_i5.ShelfItem>[],
            ),
          )
          as _i4.Future<List<_i5.ShelfItem>>);

  @override
  _i4.Future<void> saveShelfItems(String? userId, List<_i5.ShelfItem>? items) =>
      (super.noSuchMethod(
            Invocation.method(#saveShelfItems, [userId, items]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> insertShelfItem(String? userId, _i5.ShelfItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#insertShelfItem, [userId, item]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateShelfItem(String? userId, _i5.ShelfItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#updateShelfItem, [userId, item]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteShelfItem(String? userId, String? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteShelfItem, [userId, itemId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.ShelfItem?> getShelfItemById(String? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#getShelfItemById, [itemId]),
            returnValue: _i4.Future<_i5.ShelfItem?>.value(),
          )
          as _i4.Future<_i5.ShelfItem?>);

  @override
  _i4.Future<String?> getShelfItemUserId(String? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#getShelfItemUserId, [itemId]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<String?> getJournalEntryUserId(String? entryId) =>
      (super.noSuchMethod(
            Invocation.method(#getJournalEntryUserId, [entryId]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<List<_i5.JournalEntry>> getJournalEntries(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getJournalEntries, [userId]),
            returnValue: _i4.Future<List<_i5.JournalEntry>>.value(
              <_i5.JournalEntry>[],
            ),
          )
          as _i4.Future<List<_i5.JournalEntry>>);

  @override
  _i4.Future<void> saveJournalEntries(
    String? userId,
    List<_i5.JournalEntry>? entries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveJournalEntries, [userId, entries]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> insertJournalEntry(
    String? userId,
    _i5.JournalEntry? entry,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertJournalEntry, [userId, entry]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteJournalEntry(String? userId, String? entryId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteJournalEntry, [userId, entryId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> queueSyncTask({
    required String? userId,
    required String? tableName,
    required String? operation,
    required String? itemId,
    Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#queueSyncTask, [], {
              #userId: userId,
              #tableName: tableName,
              #operation: operation,
              #itemId: itemId,
              #data: data,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getPendingSyncTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPendingSyncTasks, [userId]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> deleteSyncTask(int? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSyncTask, [taskId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> migrateGuestData(String? oldUserId, String? newUserId) =>
      (super.noSuchMethod(
            Invocation.method(#migrateGuestData, [oldUserId, newUserId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllTables() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllTables, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i6.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isSyncing =>
      (super.noSuchMethod(Invocation.getter(#isSyncing), returnValue: false)
          as bool);

  @override
  _i4.Future<void> syncQueue(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#syncQueue, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> syncAndFetchShelf(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#syncAndFetchShelf, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> syncAndFetchJournal(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#syncAndFetchJournal, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
